---
title: "EDA do log de eventos"
output: html_notebook
---

## O quê

Como usamos dados derivados dos logs de eventos da wikimedia, aqui primeiro exploramos esses logs para entender como os eventos foram coletados, e para procurar características inesperadas. 

```{r}
library(tidyverse)
library(lubridate)
theme_set(theme_bw())
```

## Lendo os eventos

```{r ETL}
events = read_csv("https://github.com/wikimedia-research/Discovery-Hiring-Analyst-2016/raw/master/events_log.csv.gz")

events = events %>% slice(1:5e4) # Útil para testar código em dados pequenos. Comente na hora de processá-los para valer.

events = events %>% 
    group_by(session_id) %>% 
    arrange(timestamp) %>% 
    mutate(search_index = cumsum(action == "searchResultPage"), # contador de buscas na sessão.
           date = ymd_hms(timestamp))  %>% 
    ungroup()
```

## No tempo


```{r}
events %>% 
    mutate(date = round_date(date, unit = "day")) %>% 
   # count(date, group) %>% 
    ggplot(events, mapping = aes(x = reorder(date,result_position), y = result_position))   +
  geom_boxplot() 
   
```

```{r}
events %>% 
    ggplot(aes(x = result_position)) + 
    geom_histogram(bins = 20, fill = "white", color = "blue")  + geom_rug(alpha = .3) +  scale_x_log10() 
```


```{r}
events %>% 
 summarise( Media = mean(result_position, na.rm = TRUE),
 Mediana = median(n_results, na.rm = TRUE),
 Desvio = sd(n_results, na.rm = TRUE),  IQR = IQR(n_results, na.rm = TRUE),) 

```


```{r}

#events %>% count(n_results==0)

eventsa = events %>% 
    filter(group == "a")

eventsb = events %>% 
    filter(group == "b")

events3 = events %>% 
    filter(n_results == "0")

length(which(events$n_results==0))
length(which(eventsa$n_results==0))
length(which(eventsb$n_results==0))

ggplot(events3) + 
  geom_bar(mapping = aes(x = group), stat = "count")   


```

## Por tipo

## Etc.